spring:
  datasource:
    tenants:
      default:
        url: jdbc:postgresql://34.64.100.26:5432/history
        username: postgresql
        password: postgrespassword
        driver-class-name: org.postgresql.Driver
        project: multi
        version: real
      kakao:
        url: jdbc:postgresql://34.64.100.26:5432/kakao
        username: postgresql
        password: postgrespassword
        driver-class-name: org.postgresql.Driver
        project: multi
        version: real
      naver:
        url: jdbc:postgresql://34.64.100.26:5432/naver
        username: postgresql
        password: postgrespassword
        driver-class-name: org.postgresql.Driver
        project: multi
        version: real

