spring:
  datasource:
    tenants:
      default:
        url: jdbc:postgresql://13.209.82.159:8080/history
        username: postgresql
        password: postgrespassword
        driver-class-name: org.postgresql.Driver
        project: multi
        version: dev
      kakao:
        url: jdbc:postgresql://13.209.82.159:8080/kakao
        username: postgresql
        password: postgrespassword
        driver-class-name: org.postgresql.Driver
        project: multi
        version: dev
      naver:
        url: jdbc:postgresql://13.209.82.159:8080/naver
        username: postgresql
        password: postgrespassword
        driver-class-name: org.postgresql.Driver
        project: multi
        version: dev

