spring:
  datasource:
    tenants:
      default:
        url: jdbc:h2:mem:data/demo
        driverClassName: org.h2.Driver
        username: sa
        password:
        jpa:
          hibernate:
            ddl-auto: create-drop
        project: multi
        version: dev
      kakao:
        url: jdbc:h2:mem:data/kakao
        driverClassName: org.h2.Driver
        username: sa
        password:
        jpa:
          hibernate:
            ddl-auto: create-drop
        project: multi
        version: dev
      naver:
        url: jdbc:h2:mem:data/naver
        driverClassName: org.h2.Driver
        username: sa
        password:
        jpa:
          hibernate:
            ddl-auto: create-drop
        project: multi
        version: dev

